### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by hugobellomusto** [opencypher/front-end#23]
I wonder if this repo is still active. Contributions seem to stop suddenly in sep/2022.

**Comment by hugobellomusto** [comment]
@sherfert @Lojjs

**Comment by Lojjs** [comment]
Hi, this repo is not updated anymore. But you can find the up-to-date Neo4j frontend code in the Neo4j public repo (https://github.com/neo4j/neo4j/tree/5.15/community/cypher/front-end), with the same Apache2 license. This repo was just a copy of that one, and synchronization was stopped.

**Comment by hugobellomusto** [comment]
Thanks!
