### ISSUE TITLE
Cross published artifacts?

### ISSUE THREAD

**Issue by harpocrates** [opencypher/front-end#4]
Assuming that [`org.opencypher` on Maven](https://mvnrepository.com/artifact/org.opencypher) really is the place to fetch artifacts, it is a bit frustrating that the artifacts are not cross-published.   Artifacts appear to be built with Scala 2.12.7, but no JARS are published with the `_2.12` suffix. Here's a quick visual way to spot this on Maven: notice how [`shapeless`](https://mvnrepository.com/artifact/com.chuusai/shapeless) has a column for "Scala" but [`util-9.0`](https://mvnrepository.com/artifact/com.chuusai/shapeless) doesn't.

This is doubly problematic for Scala projects that want to use `front-end`:

  1. If possible, it would be nice to have artifacts cross-published for multiple Scala versions (I don't expect support for 2.10, 2.11, 2.12, 2.13, Scala.js, and Scala Native like Shapeless has, but perhaps 2.12 and 2.13?).

  2. At the very least, there should be artifacts published with the right `_2.12` suffix. Without that, any Scala project using another Scala version depending on `front-end` will encounter confusing run time crashes.

Thanks!

**Comment by harpocrates** [comment]
Ping! Also, is there a chance of a new release soon? It seems a fair bit has changed since the last release from 8 months ago.

**Comment by masonedmison** [comment]
bump

**Comment by mnd999** [comment]
With the Scala 2.13 upgrade, we have added the _2.13 suffixes.

**Comment by harpocrates** [comment]
Thank you! Is https://mvnrepository.com/artifact/org.opencypher the place where the artifacts will eventually be published?

**Comment by harpocrates** [comment]
@mnd999 sorry to be annoying, but are those artifacts published anywhere?

**Comment by mnd999** [comment]
That is the right location. but there isn't really an scheduled for publishing artifacts. We're currently discussing internally about how this repository should work. If you have any feedback let me know and I'll pass it on.
