### ISSUE TITLE
Prettifier does not support UNION clause 

### ISSUE THREAD

**Issue by mad** [opencypher/front-end#5]
Any query with union clause can't be prettified 

```
MATCH (n:Actor)
RETURN n.name AS name
UNION ALL MATCH (n:Movie)
RETURN n.title AS name
```

```
scala.MatchError: Query(None,UnionDistinct(SingleQuery(List(Match(... (of class org.opencypher.v9_0.ast.Query)

	at org.opencypher.v9_0.ast.prettifier.Prettifier.asString(Prettifier.scala:22)

```

Possible solutions
```
case class Prettifier(mkStringOf: ExpressionStringifier) {
  def asString(statement: Statement): String = statement match {
    case Query(_, SingleQuery(clauses)) =>
      clauses.map(dispatch).mkString(NL)
    case Query(_, union : UnionDistinct) =>
      union.unionedQueries.map(q => q.clauses.map(dispatch).mkString(NL)).mkString(NL + "UNION" + NL)
    case Query(_, union : UnionAll) =>
      union.unionedQueries.map(q => q.clauses.map(dispatch).mkString(NL)).mkString(NL + "UNION ALL" + NL)
  }
```

**Comment by bob-bierman-maritz** [comment]
I have the same issue...

**MATCH (p:Person) WHERE p.paxId < 175
UNION
MATCH (p:Person) WHERE p.paxId >= 175
RETURN p.controlNum**

scala.MatchError: Query(None,UnionDistinct(SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(Some(Variable(p)),Stream(LabelName(Person), ?),None,None)))),List(),Some(Where(LessThan(Property(Variable(p),PropertyKeyName(paxId)),SignedDecimalIntegerLiteral(175))))))),SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(Some(Variable(p)),List(LabelName(Person)),None,None)))),List(),Some(Where(GreaterThanOrEqual(Property(Variable(p),PropertyKeyName(paxId)),SignedDecimalIntegerLiteral(175))))), Return(false,ReturnItems(false,List(UnaliasedReturnItem(Property(Variable(p),PropertyKeyName(controlNum)),p.controlNum))),None,None,None,Set()))))) (of class org.opencypher.v9_0.ast.Query)

	at org.opencypher.v9_0.ast.prettifier.Prettifier.asString(Prettifier.scala:22)
	at org.neo4j.ogm.label.LabelProvider.addLabel(LabelProvider.java:115)

[]https://github.com/meistermeier/neo4j-ogm-label-extension/blob/master/src/main/java/org/neo4j/ogm/label/LabelProvider.java

My workaround is ugly, so any help is appreciated.

**Comment by sherfert** [comment]
This should have been fixed. (Actually a long time ago, apologies for only replying now.)
