### ISSUE TITLE
get error: Expected none but found UnaliasedReturnItem

### ISSUE THREAD

**Issue by bluejoe2008** [opencypher/front-end#7]
```
val pipeline = Parsing andThen SemanticAnalysis(warn = false)
val query = "match (n)-[knows]->(m) where m.age>35 return n.name"
val startState = InitialState(query, None, NoPlannerName, Map())

val context = new ErrorCollectingContext()
val r = pipeline.transform(startState, context)
```
transform() will report an error: Expected none but found UnaliasedReturnItem
does it mean that I should write `return n.name as name1`?

do you provide any well-readable test cases of handling a Cypher query?

**Comment by sherfert** [comment]
Thanks for your question. Please have a look at [CompilationPhases](https://github.com/opencypher/front-end/blob/9.0/frontend/src/main/scala/org/opencypher/v9_0/frontend/phases/CompilationPhases.scala) on how to assemble Phases in a legal fashion.

Your intuition was also right, aliasing the `ReturnItem` would have prevented this error as well.

Unfortunately we don't have any integration-tests that come with the frontend. Our integration tests of these components can be found in the [neo4j repository](https://github.com/neo4j/neo4j/tree/4.2/community/cypher/cypher-planner/src/test/scala/org/neo4j/cypher/internal/compiler/planner). They test a larger part of the stack, but I hope they can help as a resource anyway.
